Vetclinic: Create a database based on a diagram
kelomo2502/vet-clinic-data pull request #7
Opened 2022-08-30 20:28 UTC by kelomo2502

In this milestone:

- We created a file named schema_based_on_diagram.sql
- Add indexes to foreign keys

2022-08-30 22:57 UTC, ShadyShawkat requested changes
## Hi @kelomo2502, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-30 22:57 UTC, ShadyShawkat commented on schema_based_on_diagram.sql
> +name varchar(300));
- [ ] Please add the join the table between `medical_histories` and `treatments` tables as there is a many to many relation between those tables. Also, please make sure to create an index for that join table.

2022-08-30 22:57 UTC, ShadyShawkat commented on schema_based_on_diagram.sql
> +creaate index medical_history_index ON invoices(medical_history_id);
- [ ] Please correct this typo in the word `creaate`.

2022-08-31 01:02 UTC, smunozmo approved these changes
Hi @kelomo2502, 👋 

## Highlights 👏 

- Excellent job making the suggested changes, your project is complete! 😎 
- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

# APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 01:07 UTC, merged